### ISSUE TITLE
problems with deno 1.6

### ISSUE THREAD

**Issue by christianhaller** [udibo/collections#7]
````
deno test
Download https://deno.land/x/test_suite@v0.6.0/mod.ts
Download https://deno.land/x/test_suite@v0.6.0/test_suite.ts
Download https://deno.land/x/test_suite@v0.6.0/deps/udibo/collections/vector.ts
Download https://deno.land/x/collections@v0.9.1/vector.ts
Download https://deno.land/x/collections@v0.9.1/common.ts
Check file:///Users/challer/collections/$deno$test.ts
error: TS2339 [ERROR]: Property 'data' does not exist on type '(ArrayLike<T> & Vector<any>) | (Iterable<T> & Vector<any>)'.
    const data = collection instanceof Vector ? collection.data : collection;
                                                           ~~~~
    at https://deno.land/x/collections@v0.9.1/vector.ts:77:60

TS2339 [ERROR]: Property 'compare' does not exist on type '(ArrayLike<T> & BinaryHeap<any>) | (Iterable<T> & BinaryHeap<any>)'.
      result = new BinaryHeap(options?.compare ?? collection.compare);
                                                             ~~~~~~~
    at file:///Users/challer/collections/binary_heap.ts:43:62

TS2339 [ERROR]: Property 'data' does not exist on type '(ArrayLike<T> & BinaryHeap<any>) | (Iterable<T> & BinaryHeap<any>)'.
        unmappedValues = collection.data;
                                    ~~~~
    at file:///Users/challer/collections/binary_heap.ts:45:37

TS2339 [ERROR]: Property 'data' does not exist on type '(ArrayLike<T> & BinaryHeap<any>) | (Iterable<T> & BinaryHeap<any>)'.
        result.data = Array.from(collection.data);
                                            ~~~~
    at file:///Users/challer/collections/binary_heap.ts:47:45

TS2339 [ERROR]: Property 'compare' does not exist on type '(ArrayLike<T> & BSTree<any>) | (Iterable<T> & BSTree<any>)'.
      result = new Tree(options?.compare ?? collection.compare);
                                                       ~~~~~~~
    at file:///Users/challer/collections/trees/bs_tree.ts:60:56

TS2339 [ERROR]: Property 'root' does not exist on type '(ArrayLike<T> & BSTree<any>) | (Iterable<T> & BSTree<any>)'.
        if (collection.root) {
                       ~~~~
    at file:///Users/challer/collections/trees/bs_tree.ts:66:24

TS2339 [ERROR]: Property 'root' does not exist on type '(ArrayLike<T> & BSTree<any>) | (Iterable<T> & BSTree<any>)'.
          result.root = Node.from(collection.root);
                                             ~~~~
    at file:///Users/challer/collections/trees/bs_tree.ts:67:46

Found 7 errors.
````

I will look at this deeper tonight.

**Comment by KyleJune** [comment]
I'll upgrade this and my other modules Friday Night or on Saturday. Thank you for letting me know about the issue with 1.6.0.

**Comment by KyleJune** [comment]
This issue has been resolved in https://deno.land/x/test_suite@v0.6.3 and https://deno.land/x/collections@v0.10.2
