### ISSUE TITLE
Does not work with deno 1.9.0

### ISSUE THREAD

**Issue by ngruychev** [udibo/collections#8]
Trying to use this library with deno 1.9.0 fails
```
$ deno --version
deno 1.9.0 (release, x86_64-unknown-linux-gnu)
v8 9.1.269.5
typescript 4.2.2
$ deno cache https://deno.land/x/collections@v0.10.2/mod.ts
Check https://deno.land/x/collections@v0.10.2/mod.ts
error: TS2612 [ERROR]: Property 'parent' will overwrite the base property in 'BSNode<T>'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
  parent!: RBNode<T> | null;
  ~~~~~~
    at https://deno.land/x/collections@v0.10.2/trees/rb_node.ts:6:3

TS2612 [ERROR]: Property 'left' will overwrite the base property in 'BSNode<T>'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
  left!: RBNode<T> | null;
  ~~~~
    at https://deno.land/x/collections@v0.10.2/trees/rb_node.ts:7:3

TS2612 [ERROR]: Property 'right' will overwrite the base property in 'BSNode<T>'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
  right!: RBNode<T> | null;
  ~~~~~
    at https://deno.land/x/collections@v0.10.2/trees/rb_node.ts:8:3

TS2612 [ERROR]: Property 'root' will overwrite the base property in 'BSTree<T>'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
  protected root!: RBNode<T> | null;
            ~~~~
    at https://deno.land/x/collections@v0.10.2/trees/rb_tree.ts:18:13

Found 4 errors.
```

**Comment by KyleJune** [comment]
Thanks, I'll merge your PR and do a version bump for all my modules that require it on Saturday.
